# This is the main configuration file of your Dancer app
# env-related settings should go to environments/$env.yml
# all the settings in this file will be loaded at Dancer's startup.

# Your application's name
appname: "Judo::Clubmanager"

# The default layout to use for your application (located in
# views/layouts/main.tt)
layout: "main"

# when the charset is set to UTF-8 Dancer will handle for you
# all the magic of encoding and decoding. You should not care
# about unicode within your app when this setting is set (recommended).
charset: "UTF-8"

# template engine
# simple: default and very basic template engine
# template_toolkit: TT

#template: "simple"

template: "template_toolkit"
engines:
  template_toolkit:
    start_tag: '[%'
    end_tag:   '%]'

# For session support enable the following line and see Dancer::Session
# session: "YAML"
plack_middlewares:
  Debug:
    - panels
    -
      - Parameters
      - Dancer::Version
      - Dancer::Settings
      - Dancer::Logger
      - Dancer::Routes

plugins:
    Database:
        connections:
            clubs:
                driver: "SQLite"
                database: "data/clubs.sqlite"
    Auth::Extensible:
        exit_page: '/'
        realms:
            config:
                provider: Config
                users:
                    - user: admin
                      pass: admin
                      roles:
                        - Admin
                    - user: bob
                      pass: bob
                      roles:
                        - User
session: YAML

showerrors: 1
